# Generated by Django 5.0.1 on 2024-05-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'permissions': [('dashboard_access', 'Can access the dashboard'), ('reports_view', 'Can view reports'), ('reports_edit', 'Can edit reports'), ('settings_access', 'Can access settings')]},
        ),
    ]
