# Generated by Django 5.0.1 on 2024-05-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_auditlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
    ]
