# Generated by Django 5.0.1 on 2024-05-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_auditlog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='report_name',
            field=models.CharField(max_length=100),
        ),
    ]
